apiVersion: v1
kind: Deployment
metadata:
  name: task1
  labels:
    app: task1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task1-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: task1-app
    spec:
      containers:
      - image: mks1011/task1jenk
        name: task1
        env:
          - name: YOUR_NAME
            value: {{YOUR_NAME}}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: task1-app
spec:
  type: ClusterIP
  selector:
    app: task1-app
  ports:
    - port: 5500
      protocol: TCP