apiVersion: v1
kind: Service
metadata:
   name: flask-app
spec:
   type: LoadBalancer
   selector:
      app: flask
   ports:
   - protocol: TCP
     port: 5500
     targetPort: 5500
---

apiVersion: v1
kind: Pod
metadata:
    name: flask
    labels:
       app: flask
spec:
    containers:
    - name: flask
      image: mks1011/task1jenk:latest # Dockerhub
      ports:
      - containerPort: 5500